"""Rebuild the single-file bundle and generate focused runtime regression tests."""
from pathlib import Path
import json

ROOT = Path(__file__).resolve().parent
NAMES = ['aira code.txt', 'mira_deobfuscated.luaU', 'palantir timings.lua',
         'palantir_deobfuscated.lua', 'psw93dh.txt']
parts = ['''-- Generated by build_bundle.py. Requires loadstring.
-- All sources are included; only the selected entry point runs.
local environment = (getgenv and getgenv()) or _G
local sources = {}
local order = {}
''']
for name in NAMES:
    source = (ROOT / name).read_text(encoding='utf-8-sig')
    if name == 'palantir_deobfuscated.lua':
        source = (ROOT / 'log_guard.luau').read_text(encoding='utf-8') + '\n' + source
    eq = '===='
    while ']' + eq + ']' in source:
        eq += '='
    quoted = json.dumps(name)
    parts.append(f'order[#order + 1] = {quoted}\nsources[{quoted}] = ([{eq}[ {source}]{eq}]):sub(2)\n')
parts.append('''local Bundle = {}
function Bundle.list()
    return table.clone(order)
end
function Bundle.source(name)
    return sources[name]
end
function Bundle.run(name, ...)
    assert(sources[name], "Unknown bundle entry: " .. tostring(name))
    assert(type(loadstring) == "function", "This bundle requires loadstring support")
    local chunk, compileError = loadstring(sources[name], "@" .. name)
    assert(chunk, compileError)
    return chunk(...)
end
environment.PALANTIR_BUNDLE = Bundle
local entrypoint = environment.PALANTIR_BUNDLE_ENTRYPOINT or "palantir_deobfuscated.lua"
return Bundle.run(entrypoint)
''')
(ROOT / 'palantir_bundle.luau').write_text(''.join(parts), encoding='utf-8', newline='\n')

source = (ROOT / 'palantir_deobfuscated.lua').read_text(encoding='utf-8-sig')
module = source.split('v18 = "Utility/JSON"', 1)[1].split('f46(v18, condition3)', 1)[0]
button = source.split('local function f79(_, p134, ...)', 1)[1].split('f79(self, object51, ...)', 1)[0]
tests = 'local condition3\n' + module + '''
local json = condition3()
local decoded = json.decode('{"name":"test","values":[1,true,false],"escaped":"a\\\\nb"}')
assert(decoded.name == "test")
assert(decoded.values[1] == 1 and decoded.values[2] == true and decoded.values[3] == false)
assert(decoded.escaped == "a\\nb")
assert(json.decode(json.encode({message = "hello", value = 42})).value == 42)
assert(json.decode('"\\\\u0041"') == "A")
assert(not pcall(json.decode, '{bad json}'))
local function f79(_, p134, ...)
''' + button + '''
local callback = function() end
local target = {}
f79(nil, target, "Run", callback)
assert(target.Text == "Run" and target.Func == callback)
target = {}
f79(nil, target, {Text = "Confirm", Func = callback, DoubleClick = true, Tooltip = "Tip"})
assert(target.Text == "Confirm" and target.Func == callback and target.DoubleClick and target.Tooltip == "Tip")
assert(not pcall(f79, nil, {}, "Missing callback"))
print("PASS: JSON initialization, decode/encode/escapes, invalid input, button argument forms")
'''
window = source.split('f67 = function(...)', 1)[1].split('local t580 =', 1)[0]
toggle = source.split('function table56.Toggle(forceVisible)', 1)[1].split('local function f366', 1)[0]
mouse = source.split('local savedMouseBehavior, savedMouseIcon', 1)[1].split('function table56.Toggle(forceVisible)', 1)[0]
tests += '''
local Vector2 = {zero = {}, new = function(...) return {...} end}
local UDim2 = {fromOffset = function(...) return {...} end, fromScale = function(...) return {...} end}
local function windowOptions(...)
''' + window + '''
return t579
end
assert(windowOptions({}, {Title = "Window", Center = true}).Title == "Window")
assert(windowOptions({}, "Legacy", true).AutoShow == true)
assert(windowOptions({}, "Legacy", true).Title == "Legacy")
local table56 = {GiveSignal = function() end}
local v810, v811, v812, v399 = false, false, nil, false
local v804 = {Visible = false}
local v391 = {Enabled = true, Parent = {}}
local v884 = {Modal = false}
local object98 = {MouseBehavior = "LockCenter", MouseIconEnabled = false}
local t598 = {MenuFadeTime = 0}
local t64, t66, t67, t68 = {}, {}, {}, {}
local shared = {}
local Enum = {MouseBehavior = {Default = "Default"}}
local frameCallback
local disconnects = 0
local game = {GetService = function()
    return {RenderStepped = {Connect = function(_, callback)
        frameCallback = callback
        return {Disconnect = function() disconnects += 1 end}
    end}}
end}
local savedMouseBehavior, savedMouseIcon
''' + mouse + '''
function table56.Toggle(forceVisible)
''' + toggle + '''
table56.Toggle(true)
table56.Toggle(true)
assert(v804.Visible and v884.Modal)
v391.Enabled = false
frameCallback()
assert(not v884.Modal and shared._PalantirX_MouseEnforce == nil and disconnects == 1)
assert(object98.MouseBehavior == "LockCenter" and object98.MouseIconEnabled == false)
v391.Enabled = true
table56.Toggle(true)
table56.Toggle(false)
assert(not v804.Visible and not v884.Modal and disconnects == 2)
assert(object98.MouseBehavior == "LockCenter" and object98.MouseIconEnabled == false)
print("PASS: window options, repeated show, hidden-menu mouse release, explicit close")
'''
guard = (ROOT / 'log_guard.luau').read_text(encoding='utf-8')
tests += '''
do
local now = 0
local os = {clock = function() return now end}
local messages = {}
local env = {}
local getgenv = function() return env end
local warn = function(message) table.insert(messages, message) end
local print = warn
''' + guard + '''
for i = 1, 100 do warn("Repeated failure") end
assert(#messages == 1 and env.PALANTIR_LOG.suppressed == 99)
for i = 1, 20 do print("Message " .. i) end
assert(#messages == 5)
now = 11
warn("Repeated failure")
assert(#messages == 6)
for i = 1, 200 do warn("More " .. i) end
assert(#env.PALANTIR_LOG.records <= 100)
end
print("PASS: repeated-log suppression, global rate budget, window reset, bounded log history")
'''
(ROOT / 'regression_tests.luau').write_text(tests, encoding='utf-8', newline='\n')
print('Rebuilt palantir_bundle.luau and regression_tests.luau')
